steps:

# Download SSH encrypted private key and SSH known hosts file
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/github_id_rsa.enc', '/root/.ssh/github_id_rsa.enc']
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/github_known_hosts', '/root/.ssh/known_hosts']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Download `go mod` cache file
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if gsutil -q stat gs://${PROJECT_ID}_cloudbuild/gomod-cache.tar.gz; then
        echo "Fetching gomod cache"
        gsutil cp gs://${PROJECT_ID}_cloudbuild/gomod-cache.tar.gz ./
        tar -xpzf gomod-cache.tar.gz -C /builder/home/go/pkg/mod/cache
        echo "Succesfully fetched gomod cache"
      else
        echo "No gomod cache"
      fi
  volumes:
  - name: 'gocache'
    path: /builder/home/go/pkg/mod/cache

# Decrypting SSH encrypted private key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --project=eoscanada-public
  - --ciphertext-file=/root/.ssh/github_id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=github-keys
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Initializing Git with SSH credentials and URL transformation
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    git config --global --add url."git@github.com:".insteadOf "https://github.com/"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git'
    path: /root/.git

# Perform the actual build/test step of the project
- id: gobuild
  name: gcr.io/cloud-builders/go:debian
  entrypoint: 'sh'
  env:
  - CGO_ENABLED=0
  args:
  - '-cxe'
  - |
    cd /workspace
    go test -v ./...
    go build -v -o /root/artifacts/$_APP .
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git'
    path: /root/.git
  - name: 'gocache'
    path: /builder/home/go/pkg/mod/cache
  - name: 'artifacts'
    path: /root/artifacts

# Upload updated `go mod` cache file
#- name: 'gcr.io/cloud-builders/gsutil'
#  entrypoint: 'sh'
#  args:
#    - '-c'
#    - |
#      cd /builder/home/go/pkg/mod/cache
#      tar czf gomod-cache.tar.gz download
#      gsutil cp gomod-cache.tar.gz gs://${PROJECT_ID}_cloudbuild/gomod-cache.tar.gz
#  volumes:
#  - name: 'gocache'
#    path: /builder/home/go/pkg/mod/cache

# Build Docker
- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_APP:$TAG_NAME',
    '-t', 'gcr.io/$PROJECT_ID/$_APP:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_APP:latest',
    '-f', 'deploy/Dockerfile',
    '/root/artifacts'
  ]
  volumes:
  - name: 'artifacts'
    path: /root/artifacts


images:
- gcr.io/$PROJECT_ID/$_APP:$TAG_NAME
- gcr.io/$PROJECT_ID/$_APP:latest
